Fix Bidirection noise
chronoz-isl/zeus-robot pull request #14
Opened 2017-08-28 09:39 UTC by best25792

2017-08-29 04:56 UTC, kkalavantavanich requested changes
'n++' bug

2017-08-29 15:13 UTC, kkalavantavanich commented
Delete main.cpp ???

2017-08-29 15:16 UTC, kkalavantavanich commented on _main.cpp
> +	int clint direction_checkediff_history[4] = { 0, 0, 0, 0 };
'clint' -> cliff_history[4] & direction_checked ??

2017-08-29 15:59 UTC, best25792 commented on _main.cpp
> +	int clint direction_checkediff_history[4] = { 0, 0, 0, 0 };
ok

2017-08-31 05:47 UTC, kkalavantavanich approved these changes

2017-08-31 05:47 UTC, merged